spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=config-client
spring.cloud.config.profile=local
spring.application.name=businessdomain-customer

eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
#for indicate that this service should be registered as an available service
eureka.client.register-with-eureka=true
#for checking the health of the service
eureka.client.healthcheck.enabled=true
#it lets the client know that they should download the list of services registered in Eureka
eureka.client.fetch-registry=true

spring.cloud.config.enabled=true
#it's going to expose all the endpoints available with Actuator of this microservice
management.endpoints.web.exposure.include=*


#spring.application.name=config-client
#spring.profiles.active=local
#spring.config.import=optional:configserver:http://localhost:8888
#spring.cloud.bootstrap.enabled=true

# Para debug
#logging.level.org.springframework.cloud=DEBUG
#logging.level.org.springframework.boot.context.config=DEBUG