spring.application.name=eureka server
server.port=8761

#each server is a client itself, these properties is used to disable the registration of the eureka server itself
eureka.client.register-with-eureka=false 

eureka.client.fetch-registry=false

#control point, useful for knowing if the eureka server is up and running correctly
eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

spring.cloud.config.enabled=false
